version: "3"
services:
  nginx:
    image: nginx:1.14-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ca.crt:/etc/nginx/server.crt:ro
      - ./ca.key:/etc/nginx/server.key:ro
    restart: always
    depends_on:
      - grpc_service

  grpc_service:
    image: cheab/simple_grpc:1.0.0
    container_name: simple_grpc
    restart: always
