# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: spec.proto for package 'simple_grpc'

require 'grpc'
require 'spec_pb'

module SimpleGrpc
  module HealthCheck
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'simple_grpc.HealthCheck'

      rpc :Ping, PingRequest, PingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
