# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "simple_grpc.PingRequest" do
  end
  add_message "simple_grpc.PingResponse" do
    optional :stat, :string, 1
  end
end

module SimpleGrpc
  PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("simple_grpc.PingRequest").msgclass
  PingResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("simple_grpc.PingResponse").msgclass
end
