# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import spec_pb2 as spec__pb2


class HealthCheckStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/simple_grpc.HealthCheck/Ping',
        request_serializer=spec__pb2.PingRequest.SerializeToString,
        response_deserializer=spec__pb2.PingResponse.FromString,
        )


class HealthCheckServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=spec__pb2.PingRequest.FromString,
          response_serializer=spec__pb2.PingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'simple_grpc.HealthCheck', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
