# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spec.proto',
  package='simple_grpc',
  syntax='proto3',
  serialized_pb=_b('\n\nspec.proto\x12\x0bsimple_grpc\"\r\n\x0bPingRequest\"\x1c\n\x0cPingResponse\x12\x0c\n\x04stat\x18\x01 \x01(\t2L\n\x0bHealthCheck\x12=\n\x04Ping\x12\x18.simple_grpc.PingRequest\x1a\x19.simple_grpc.PingResponse\"\x00\x62\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='simple_grpc.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=40,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='simple_grpc.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat', full_name='simple_grpc.PingResponse.stat', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'spec_pb2'
  # @@protoc_insertion_point(class_scope:simple_grpc.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESPONSE,
  __module__ = 'spec_pb2'
  # @@protoc_insertion_point(class_scope:simple_grpc.PingResponse)
  ))
_sym_db.RegisterMessage(PingResponse)



_HEALTHCHECK = _descriptor.ServiceDescriptor(
  name='HealthCheck',
  full_name='simple_grpc.HealthCheck',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=72,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='simple_grpc.HealthCheck.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEALTHCHECK)

DESCRIPTOR.services_by_name['HealthCheck'] = _HEALTHCHECK

# @@protoc_insertion_point(module_scope)
